language: node_js
node_js:
  - 14
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - abcdkh1209@icloud.com
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy
  - cp package.json before-deploy
  - cp -r src before-deploy
  - cp appspec.yml before-deploy
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/pocket-backend.zip
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: clroot-pocket-backend-deploy
    region: ap-northeast-2
    acl: private
    local_dir: deploy
    on:
      repo: clroot/pocket-backend
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: clroot-pocket-backend-deploy
    key: pocket-backend.zip
    bundle_type: zip
    application: pocket-backend
    deployment_group: pocket-backend-deploy
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: clroot/pocket-backend
      branch: master
