language: node_js
node_js:
  - 14
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - abcdkh1209@icloud.com
before_deploy:
  - rm -rf node_modules
  - zip -r pocket-backend *
  - mkdir -p deploy
  - mv pocket-backend.zip deploy/pocket-backend.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: pocket-backend-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: clroot/pocket-backend
      branch: master
