language: node_js
node_js:
  - 14
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - abcdkh1209@icloud.com
before_deploy:
  - rm -rf node_modules
  - zip -r pocket-backend *
  - mkdir -p deploy
  - mv pocket-backend.zip deploy/pocket-backend.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: pocket-backend-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: clroot/pocket-backend
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: pocket-backend-deploy # S3 버킷
    key: pocket-backend.zip
    bundle_type: zip
    application: pocket-backend # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: pocket-backend-deploy
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: clroot/pocket-backend
      branch: master
